name: scientific_programming123
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyter
  - nodejs
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - mpl_sample_data
  - pandas
  - statsmodels
  - seaborn
  - plotnine
  - pivottablejs
  - pandas-profiling
  - altair
  - vega_datasets
  - numba
  - pytest
  - cython
  - tqdm
  - markdown
  - plotly
  - conda-forge::psychopy
  - pip:
    - expyriment
    - pygame
    #- jupyterlab-solutions
    - jupyterlab_code_formatter
    - nb_black
    - ipympl
    - pySerial
    - tqdm
    - cleanipynb
    - mypy
    #psychopy
    - psychtoolbox
    - pyo
    - pyparallel; platform_system != "Windows"
    - SoundFile; platform_system == "Windows"